package com.vipro.data;

// Generated Feb 3, 2013 6:50:08 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * AccountAging generated by hbm2java
 */
public class AccountAging implements java.io.Serializable {

	private Long accountAgingId;
	private Account account;
	private String agingType;
	private Date agingStartDate;
	private BigDecimal delinquentLevel1;
	private BigDecimal delinquentLevel2;
	private BigDecimal delinquentLevel3;
	private BigDecimal delinquentLevel4;
	private BigDecimal delinquentLevel5;
	private BigDecimal delinquentLevel6;
	private BigDecimal delinquentLevel7;
	private BigDecimal delinquentLevel8;
	private BigDecimal delinquentLevel9;
	private BigDecimal delinquentLevel10;
	private BigDecimal delinquentLevel11;
	private BigDecimal delinquentLevel12;

	public AccountAging() {
	}

	public AccountAging(Account account) {
		this.account = account;
	}

	public AccountAging(Account account, String agingType, Date agingStartDate,
			BigDecimal delinquentLevel1, BigDecimal delinquentLevel2,
			BigDecimal delinquentLevel3, BigDecimal delinquentLevel4,
			BigDecimal delinquentLevel5, BigDecimal delinquentLevel6,
			BigDecimal delinquentLevel7, BigDecimal delinquentLevel8,
			BigDecimal delinquentLevel9, BigDecimal delinquentLevel10,
			BigDecimal delinquentLevel11, BigDecimal delinquentLevel12) {
		this.account = account;
		this.agingType = agingType;
		this.agingStartDate = agingStartDate;
		this.delinquentLevel1 = delinquentLevel1;
		this.delinquentLevel2 = delinquentLevel2;
		this.delinquentLevel3 = delinquentLevel3;
		this.delinquentLevel4 = delinquentLevel4;
		this.delinquentLevel5 = delinquentLevel5;
		this.delinquentLevel6 = delinquentLevel6;
		this.delinquentLevel7 = delinquentLevel7;
		this.delinquentLevel8 = delinquentLevel8;
		this.delinquentLevel9 = delinquentLevel9;
		this.delinquentLevel10 = delinquentLevel10;
		this.delinquentLevel11 = delinquentLevel11;
		this.delinquentLevel12 = delinquentLevel12;
	}

	public Long getAccountAgingId() {
		return this.accountAgingId;
	}

	public void setAccountAgingId(Long accountAgingId) {
		this.accountAgingId = accountAgingId;
	}

	public Account getAccount() {
		return this.account;
	}

	public void setAccount(Account account) {
		this.account = account;
	}

	public String getAgingType() {
		return this.agingType;
	}

	public void setAgingType(String agingType) {
		this.agingType = agingType;
	}

	public Date getAgingStartDate() {
		return this.agingStartDate;
	}

	public void setAgingStartDate(Date agingStartDate) {
		this.agingStartDate = agingStartDate;
	}

	public BigDecimal getDelinquentLevel1() {
		return this.delinquentLevel1;
	}

	public void setDelinquentLevel1(BigDecimal delinquentLevel1) {
		this.delinquentLevel1 = delinquentLevel1;
	}

	public BigDecimal getDelinquentLevel2() {
		return this.delinquentLevel2;
	}

	public void setDelinquentLevel2(BigDecimal delinquentLevel2) {
		this.delinquentLevel2 = delinquentLevel2;
	}

	public BigDecimal getDelinquentLevel3() {
		return this.delinquentLevel3;
	}

	public void setDelinquentLevel3(BigDecimal delinquentLevel3) {
		this.delinquentLevel3 = delinquentLevel3;
	}

	public BigDecimal getDelinquentLevel4() {
		return this.delinquentLevel4;
	}

	public void setDelinquentLevel4(BigDecimal delinquentLevel4) {
		this.delinquentLevel4 = delinquentLevel4;
	}

	public BigDecimal getDelinquentLevel5() {
		return this.delinquentLevel5;
	}

	public void setDelinquentLevel5(BigDecimal delinquentLevel5) {
		this.delinquentLevel5 = delinquentLevel5;
	}

	public BigDecimal getDelinquentLevel6() {
		return this.delinquentLevel6;
	}

	public void setDelinquentLevel6(BigDecimal delinquentLevel6) {
		this.delinquentLevel6 = delinquentLevel6;
	}

	public BigDecimal getDelinquentLevel7() {
		return this.delinquentLevel7;
	}

	public void setDelinquentLevel7(BigDecimal delinquentLevel7) {
		this.delinquentLevel7 = delinquentLevel7;
	}

	public BigDecimal getDelinquentLevel8() {
		return this.delinquentLevel8;
	}

	public void setDelinquentLevel8(BigDecimal delinquentLevel8) {
		this.delinquentLevel8 = delinquentLevel8;
	}

	public BigDecimal getDelinquentLevel9() {
		return this.delinquentLevel9;
	}

	public void setDelinquentLevel9(BigDecimal delinquentLevel9) {
		this.delinquentLevel9 = delinquentLevel9;
	}

	public BigDecimal getDelinquentLevel10() {
		return this.delinquentLevel10;
	}

	public void setDelinquentLevel10(BigDecimal delinquentLevel10) {
		this.delinquentLevel10 = delinquentLevel10;
	}

	public BigDecimal getDelinquentLevel11() {
		return this.delinquentLevel11;
	}

	public void setDelinquentLevel11(BigDecimal delinquentLevel11) {
		this.delinquentLevel11 = delinquentLevel11;
	}

	public BigDecimal getDelinquentLevel12() {
		return this.delinquentLevel12;
	}

	public void setDelinquentLevel12(BigDecimal delinquentLevel12) {
		this.delinquentLevel12 = delinquentLevel12;
	}

}
