package com.vipro.data;

// Generated Feb 3, 2013 6:50:08 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Transient;

/**
 * Address generated by hbm2java
 */
public class Address implements java.io.Serializable {

	private Long addressId;
	private Account account;
	private Customer customer;
	private String addressType;
	private String addressLine1;
	private String addressLine2;
	private String addressLine3;
	private String addressLine4;
	private String postcode;
	private String city;
	private String state;
	private String country;
	private Date createdOn;
	private String createdBy;

	public Address() {
	}

	public Address(Account account, Customer customer) {
		this.account = account;
		this.customer = customer;
	}

	public Address(Account account, Customer customer, String addressType,
			String addressLine1, String addressLine2, String addressLine3,
			String postcode, String city, String state, String country,
			Date createdOn, String createdBy) {
		this.account = account;
		this.customer = customer;
		this.addressType = addressType;
		this.addressLine1 = addressLine1;
		this.addressLine2 = addressLine2;
		this.addressLine3 = addressLine3;
		this.postcode = postcode;
		this.city = city;
		this.state = state;
		this.country = country;
		this.createdOn = createdOn;
		this.createdBy = createdBy;
	}

	public Long getAddressId() {
		return this.addressId;
	}

	public void setAddressId(Long addressId) {
		this.addressId = addressId;
	}

	public Account getAccount() {
		return this.account;
	}

	public void setAccount(Account account) {
		this.account = account;
	}

	public Customer getCustomer() {
		return this.customer;
	}

	public void setCustomer(Customer customer) {
		this.customer = customer;
	}

	public String getAddressType() {
		return this.addressType;
	}

	public void setAddressType(String addressType) {
		this.addressType = addressType;
	}

	public String getAddressLine1() {
		return this.addressLine1;
	}

	public void setAddressLine1(String addressLine1) {
		this.addressLine1 = addressLine1;
	}

	public String getAddressLine2() {
		return this.addressLine2;
	}

	public void setAddressLine2(String addressLine2) {
		this.addressLine2 = addressLine2;
	}

	public String getAddressLine3() {
		return this.addressLine3;
	}

	public void setAddressLine3(String addressLine3) {
		this.addressLine3 = addressLine3;
	}

	public String getPostcode() {
		return this.postcode;
	}

	public void setPostcode(String postcode) {
		this.postcode = postcode;
	}

	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	public Date getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	public String getAddressLine4() {
		return addressLine4;
	}

	public void setAddressLine4(String addressLine4) {
		this.addressLine4 = addressLine4;
	}

	@Override
	public String toString() {
		return "Address ["
				+ (addressId != null ? "addressId=" + addressId + ", " : "")
				+ (addressType != null ? "addressType=" + addressType + ", "
						: "")
				+ (addressLine1 != null ? "addressLine1=" + addressLine1 + ", "
						: "")
				+ (addressLine2 != null ? "addressLine2=" + addressLine2 + ", "
						: "")
				+ (addressLine3 != null ? "addressLine3=" + addressLine3 + ", "
						: "")
				+ (addressLine4 != null ? "addressLine4=" + addressLine4 + ", "
						: "")
				+ (postcode != null ? "postcode=" + postcode + ", " : "")
				+ (city != null ? "city=" + city + ", " : "")
				+ (state != null ? "state=" + state + ", " : "")
				+ (country != null ? "country=" + country + ", " : "")
				+ (createdOn != null ? "createdOn=" + createdOn + ", " : "")
				+ (createdBy != null ? "createdBy=" + createdBy : "") + "]";
	}
	
}
