package com.vipro.data;

// Generated Feb 3, 2013 6:50:08 PM by Hibernate Tools 3.4.0.CR1

/**
 * BusinessPartner generated by hbm2java
 */
public class BusinessPartner implements java.io.Serializable {

	private BusinessPartnerId id;
	private Institution institution;

	public BusinessPartner() {
	}

	public BusinessPartner(BusinessPartnerId id, Institution institution) {
		this.id = id;
		this.institution = institution;
	}

	public BusinessPartnerId getId() {
		return this.id;
	}

	public void setId(BusinessPartnerId id) {
		this.id = id;
	}

	public Institution getInstitution() {
		return this.institution;
	}

	public void setInstitution(Institution institution) {
		this.institution = institution;
	}

}
