package com.vipro.data;

// Generated Feb 7, 2013 12:56:10 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Case generated by hbm2java
 */
public class Case implements java.io.Serializable {

	private Long caseId;
	private UserProfile userProfileBySenderId;
	private Customer customer;
	private UserProfile userProfileByCreatorId;
	private UserProfile userProfileByAssigneeId;
	private Date creationDate;
	private String caseType;
	private String subject;
	private String name;
	private String mobileNo;
	private String email;
	private Date dueDate;
	private Character notification;
	private String status;
	private Set caseActivities = new HashSet(0);

	public Case() {
	}

	public Case(UserProfile userProfileBySenderId, Customer customer,
			UserProfile userProfileByCreatorId,
			UserProfile userProfileByAssigneeId) {
		this.userProfileBySenderId = userProfileBySenderId;
		this.customer = customer;
		this.userProfileByCreatorId = userProfileByCreatorId;
		this.userProfileByAssigneeId = userProfileByAssigneeId;
	}

	public Case(UserProfile userProfileBySenderId, Customer customer,
			UserProfile userProfileByCreatorId,
			UserProfile userProfileByAssigneeId, Date creationDate,
			String caseType, String subject, String name, String mobileNo,
			String email, Date dueDate, Character notification, String status,
			Set caseActivities) {
		this.userProfileBySenderId = userProfileBySenderId;
		this.customer = customer;
		this.userProfileByCreatorId = userProfileByCreatorId;
		this.userProfileByAssigneeId = userProfileByAssigneeId;
		this.creationDate = creationDate;
		this.caseType = caseType;
		this.subject = subject;
		this.name = name;
		this.mobileNo = mobileNo;
		this.email = email;
		this.dueDate = dueDate;
		this.notification = notification;
		this.status = status;
		this.caseActivities = caseActivities;
	}

	public Long getCaseId() {
		return this.caseId;
	}

	public void setCaseId(Long caseId) {
		this.caseId = caseId;
	}

	public UserProfile getUserProfileBySenderId() {
		return this.userProfileBySenderId;
	}

	public void setUserProfileBySenderId(UserProfile userProfileBySenderId) {
		this.userProfileBySenderId = userProfileBySenderId;
	}

	public Customer getCustomer() {
		return this.customer;
	}

	public void setCustomer(Customer customer) {
		this.customer = customer;
	}

	public UserProfile getUserProfileByCreatorId() {
		return this.userProfileByCreatorId;
	}

	public void setUserProfileByCreatorId(UserProfile userProfileByCreatorId) {
		this.userProfileByCreatorId = userProfileByCreatorId;
	}

	public UserProfile getUserProfileByAssigneeId() {
		return this.userProfileByAssigneeId;
	}

	public void setUserProfileByAssigneeId(UserProfile userProfileByAssigneeId) {
		this.userProfileByAssigneeId = userProfileByAssigneeId;
	}

	public Date getCreationDate() {
		return this.creationDate;
	}

	public void setCreationDate(Date creationDate) {
		this.creationDate = creationDate;
	}

	public String getCaseType() {
		return this.caseType;
	}

	public void setCaseType(String caseType) {
		this.caseType = caseType;
	}

	public String getSubject() {
		return this.subject;
	}

	public void setSubject(String subject) {
		this.subject = subject;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getMobileNo() {
		return this.mobileNo;
	}

	public void setMobileNo(String mobileNo) {
		this.mobileNo = mobileNo;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public Date getDueDate() {
		return this.dueDate;
	}

	public void setDueDate(Date dueDate) {
		this.dueDate = dueDate;
	}

	public Character getNotification() {
		return this.notification;
	}

	public void setNotification(Character notification) {
		this.notification = notification;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public Set getCaseActivities() {
		return this.caseActivities;
	}

	public void setCaseActivities(Set caseActivities) {
		this.caseActivities = caseActivities;
	}

}
