package com.vipro.data;

// Generated Feb 3, 2013 6:50:08 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * CodeHeader generated by hbm2java
 */
public class CodeHeader implements java.io.Serializable {

	private String codeHeaderId;
	private String name;
	private Set codeDets = new HashSet(0);

	public CodeHeader() {
	}

	public CodeHeader(String codeHeaderId) {
		this.codeHeaderId = codeHeaderId;
	}

	public CodeHeader(String codeHeaderId, String name, Set codeDets) {
		this.codeHeaderId = codeHeaderId;
		this.name = name;
		this.codeDets = codeDets;
	}

	public String getCodeHeaderId() {
		return this.codeHeaderId;
	}

	public void setCodeHeaderId(String codeHeaderId) {
		this.codeHeaderId = codeHeaderId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Set getCodeDets() {
		return this.codeDets;
	}

	public void setCodeDets(Set codeDets) {
		this.codeDets = codeDets;
	}

}
