package com.vipro.data;

// Generated Feb 3, 2013 6:50:08 PM by Hibernate Tools 3.4.0.CR1

/**
 * CodeDet generated by hbm2java
 */
public class CodeDet implements java.io.Serializable {

	private CodeDetId id;
	private CodeHeader codeHeader;
	private String description;
	private String status;

	public CodeDet() {
	}

	public CodeDet(CodeDetId id, CodeHeader codeHeader) {
		this.id = id;
		this.codeHeader = codeHeader;
	}

	public CodeDet(CodeDetId id, CodeHeader codeHeader, String description,
			String status) {
		this.id = id;
		this.codeHeader = codeHeader;
		this.description = description;
		this.status = status;
	}

	public CodeDetId getId() {
		return this.id;
	}

	public void setId(CodeDetId id) {
		this.id = id;
	}

	public CodeHeader getCodeHeader() {
		return this.codeHeader;
	}

	public void setCodeHeader(CodeHeader codeHeader) {
		this.codeHeader = codeHeader;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

}
