package com.vipro.data;

// Generated Feb 3, 2013 6:50:08 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Customer generated by hbm2java
 */
public class Customer implements java.io.Serializable {

	private Long customerId;
	private Institution institution;
	private String customerCategory;
	private String identityType;
	private String identityNo;
	private String title;
	private String fullName;
	private String specialHandling;
	private String race;
	private String bumiIndicator;
	private String sex;
	private String maritalStatus;
	private String employerName;
	private String houseTelNo;
	private String officeTelNo;
	private String faxNo;
	private String communicationType;
	private String language;
	private Date dateOfBirth;
	private String createdBy;
	private Date dateCreated;
	private Set addresses = new HashSet(0);
	private Set accounts = new HashSet(0);
	private Set emails = new HashSet(0);
	private Set joinAccounts = new HashSet(0);
	private Set mobilePhones = new HashSet(0);
	private Set contacts = new HashSet(0);
	private Set vouchers = new HashSet(0);
	
	private Long addressId;
	private Long emailId;
	private Long mobileId;

	public Customer() {
	}

	public Customer(Institution institution) {
		this.institution = institution;
	}

	public Customer(Institution institution, String customerCategory,
			String identityType, String identityNo, String title,
			String fullName, String specialHandling, String race,
			String bumiIndicator, String sex, String maritalStatus,
			String employerName, String houseTelNo, String officeTelNo,
			String faxNo, String communicationType, String language,
			Date dateOfBirth, String createdBy, Date dateCreated,
			Set addresses, Set accounts, Set emails, Set joinAccounts,
			Set mobilePhones, Set contacts, Set vouchers) {
		this.institution = institution;
		this.customerCategory = customerCategory;
		this.identityType = identityType;
		this.identityNo = identityNo;
		this.title = title;
		this.fullName = fullName;
		this.specialHandling = specialHandling;
		this.race = race;
		this.bumiIndicator = bumiIndicator;
		this.sex = sex;
		this.maritalStatus = maritalStatus;
		this.employerName = employerName;
		this.houseTelNo = houseTelNo;
		this.officeTelNo = officeTelNo;
		this.faxNo = faxNo;
		this.communicationType = communicationType;
		this.language = language;
		this.dateOfBirth = dateOfBirth;
		this.createdBy = createdBy;
		this.dateCreated = dateCreated;
		this.addresses = addresses;
		this.accounts = accounts;
		this.emails = emails;
		this.joinAccounts = joinAccounts;
		this.mobilePhones = mobilePhones;
		this.contacts = contacts;
		this.vouchers = vouchers;
	}

	public Long getCustomerId() {
		return this.customerId;
	}

	public void setCustomerId(Long customerId) {
		this.customerId = customerId;
	}

	public Institution getInstitution() {
		return this.institution;
	}

	public void setInstitution(Institution institution) {
		this.institution = institution;
	}

	public String getCustomerCategory() {
		return this.customerCategory;
	}

	public void setCustomerCategory(String customerCategory) {
		this.customerCategory = customerCategory;
	}

	public String getIdentityType() {
		return this.identityType;
	}

	public void setIdentityType(String identityType) {
		this.identityType = identityType;
	}

	public String getIdentityNo() {
		return this.identityNo;
	}

	public void setIdentityNo(String identityNo) {
		this.identityNo = identityNo;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getFullName() {
		return this.fullName;
	}

	public void setFullName(String fullName) {
		this.fullName = fullName;
	}

	public String getSpecialHandling() {
		return this.specialHandling;
	}

	public void setSpecialHandling(String specialHandling) {
		this.specialHandling = specialHandling;
	}

	public String getRace() {
		return this.race;
	}

	public void setRace(String race) {
		this.race = race;
	}

	public String getBumiIndicator() {
		return this.bumiIndicator;
	}

	public void setBumiIndicator(String bumiIndicator) {
		this.bumiIndicator = bumiIndicator;
	}

	public String getSex() {
		return this.sex;
	}

	public void setSex(String sex) {
		this.sex = sex;
	}

	public String getMaritalStatus() {
		return this.maritalStatus;
	}

	public void setMaritalStatus(String maritalStatus) {
		this.maritalStatus = maritalStatus;
	}

	public String getEmployerName() {
		return this.employerName;
	}

	public void setEmployerName(String employerName) {
		this.employerName = employerName;
	}

	public String getHouseTelNo() {
		return this.houseTelNo;
	}

	public void setHouseTelNo(String houseTelNo) {
		this.houseTelNo = houseTelNo;
	}

	public String getOfficeTelNo() {
		return this.officeTelNo;
	}

	public void setOfficeTelNo(String officeTelNo) {
		this.officeTelNo = officeTelNo;
	}

	public String getFaxNo() {
		return this.faxNo;
	}

	public void setFaxNo(String faxNo) {
		this.faxNo = faxNo;
	}

	public String getCommunicationType() {
		return this.communicationType;
	}

	public void setCommunicationType(String communicationType) {
		this.communicationType = communicationType;
	}

	public String getLanguage() {
		return this.language;
	}

	public void setLanguage(String language) {
		this.language = language;
	}

	public Date getDateOfBirth() {
		return this.dateOfBirth;
	}

	public void setDateOfBirth(Date dateOfBirth) {
		this.dateOfBirth = dateOfBirth;
	}

	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	public Date getDateCreated() {
		return this.dateCreated;
	}

	public void setDateCreated(Date dateCreated) {
		this.dateCreated = dateCreated;
	}

	public Set getAddresses() {
		return this.addresses;
	}

	public void setAddresses(Set addresses) {
		this.addresses = addresses;
	}

	public Set getAccounts() {
		return this.accounts;
	}

	public void setAccounts(Set accounts) {
		this.accounts = accounts;
	}

	public Set getEmails() {
		return this.emails;
	}

	public void setEmails(Set emails) {
		this.emails = emails;
	}

	public Set getJoinAccounts() {
		return this.joinAccounts;
	}

	public void setJoinAccounts(Set joinAccounts) {
		this.joinAccounts = joinAccounts;
	}

	public Set getMobilePhones() {
		return this.mobilePhones;
	}

	public void setMobilePhones(Set mobilePhones) {
		this.mobilePhones = mobilePhones;
	}

	public Set getContacts() {
		return this.contacts;
	}

	public void setContacts(Set contacts) {
		this.contacts = contacts;
	}

	public Set getVouchers() {
		return this.vouchers;
	}

	public void setVouchers(Set vouchers) {
		this.vouchers = vouchers;
	}

	public Long getAddressId() {
		return addressId;
	}

	public void setAddressId(Long addressId) {
		this.addressId = addressId;
	}

	public Long getEmailId() {
		return emailId;
	}

	public void setEmailId(Long emailId) {
		this.emailId = emailId;
	}

	public Long getMobileId() {
		return mobileId;
	}

	public void setMobileId(Long mobileId) {
		this.mobileId = mobileId;
	}

}
