package com.vipro.data;

// Generated Feb 3, 2013 6:50:08 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Email generated by hbm2java
 */
public class Email implements java.io.Serializable {

	private Long emailId;
	private Account account;
	private Customer customer;
	private String emailAddress;
	private Date createdOn;
	private String createdBy;

	public Email() {
	}

	public Email(Account account, Customer customer) {
		this.account = account;
		this.customer = customer;
	}

	public Email(Account account, Customer customer, String emailAddress,
			Date createdOn, String createdBy) {
		this.account = account;
		this.customer = customer;
		this.emailAddress = emailAddress;
		this.createdOn = createdOn;
		this.createdBy = createdBy;
	}

	public Long getEmailId() {
		return this.emailId;
	}

	public void setEmailId(Long emailId) {
		this.emailId = emailId;
	}

	public Account getAccount() {
		return this.account;
	}

	public void setAccount(Account account) {
		this.account = account;
	}

	public Customer getCustomer() {
		return this.customer;
	}

	public void setCustomer(Customer customer) {
		this.customer = customer;
	}

	public String getEmailAddress() {
		return this.emailAddress;
	}

	public void setEmailAddress(String emailAddress) {
		this.emailAddress = emailAddress;
	}

	public Date getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

}
