package com.vipro.data;

// Generated Feb 3, 2013 6:50:08 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * PostdatedCheque generated by hbm2java
 */
public class PostdatedCheque implements java.io.Serializable {

	private Long chequeId;
	private Account account;
	private Date transactionDate;
	private Date chequeValidDate;
	private BigDecimal chequeAmount;
	private String chequeNo;
	private String bankName;
	private String transactionCode;
	private String chequeStatus;

	public PostdatedCheque() {
	}

	public PostdatedCheque(Account account) {
		this.account = account;
	}

	public PostdatedCheque(Account account, Date transactionDate,
			Date chequeValidDate, BigDecimal chequeAmount, String chequeNo,
			String bankName, String transactionCode, String chequeStatus) {
		this.account = account;
		this.transactionDate = transactionDate;
		this.chequeValidDate = chequeValidDate;
		this.chequeAmount = chequeAmount;
		this.chequeNo = chequeNo;
		this.bankName = bankName;
		this.transactionCode = transactionCode;
		this.chequeStatus = chequeStatus;
	}

	public Long getChequeId() {
		return this.chequeId;
	}

	public void setChequeId(Long chequeId) {
		this.chequeId = chequeId;
	}

	public Account getAccount() {
		return this.account;
	}

	public void setAccount(Account account) {
		this.account = account;
	}

	public Date getTransactionDate() {
		return this.transactionDate;
	}

	public void setTransactionDate(Date transactionDate) {
		this.transactionDate = transactionDate;
	}

	public Date getChequeValidDate() {
		return this.chequeValidDate;
	}

	public void setChequeValidDate(Date chequeValidDate) {
		this.chequeValidDate = chequeValidDate;
	}

	public BigDecimal getChequeAmount() {
		return this.chequeAmount;
	}

	public void setChequeAmount(BigDecimal chequeAmount) {
		this.chequeAmount = chequeAmount;
	}

	public String getChequeNo() {
		return this.chequeNo;
	}

	public void setChequeNo(String chequeNo) {
		this.chequeNo = chequeNo;
	}

	public String getBankName() {
		return this.bankName;
	}

	public void setBankName(String bankName) {
		this.bankName = bankName;
	}

	public String getTransactionCode() {
		return this.transactionCode;
	}

	public void setTransactionCode(String transactionCode) {
		this.transactionCode = transactionCode;
	}

	public String getChequeStatus() {
		return this.chequeStatus;
	}

	public void setChequeStatus(String chequeStatus) {
		this.chequeStatus = chequeStatus;
	}

}
