package com.vipro.data;

// Generated Feb 3, 2013 6:50:08 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * ProjectInventory generated by hbm2java
 */
public class ProjectInventory implements java.io.Serializable {

	private Long inventoryId;
	private Project project;
	private String unitNo;
	private String ptNo;
	private String hsdNo;
	private String blockNo;
	private Short level;
	private String layoutType;
	private String orientation;
	private Integer landArea;
	private Integer builtUpArea;
	private String propertyStatus;
	private Date statusChangeDate;
	private BigDecimal purchasePrice;
	private BigDecimal discountAmount;
	private BigDecimal redemptionAmount;
	private Date redemptionPaidTodate;
	private BigDecimal assessment;
	private BigDecimal quitRent;
	private BigDecimal legalFee;
	private BigDecimal disbursementFee;
	private String propertyAddress;
	private String propertyTitleType;
	private Date strataTitleObtainedDate;
	private Date keyHandoverDate;
	private Short developmentStage;
	private Set accounts = new HashSet(0);
	private Set progressiveBillings = new HashSet(0);

	public ProjectInventory() {
	}

	public ProjectInventory(Project project) {
		this.project = project;
	}

	public ProjectInventory(Project project, String unitNo, String ptNo,
			String hsdNo, String blockNo, Short level, String layoutType,
			String orientation, Integer landArea, Integer builtUpArea,
			String propertyStatus, Date statusChangeDate,
			BigDecimal purchasePrice, BigDecimal discountAmount,
			BigDecimal redemptionAmount, Date redemptionPaidTodate,
			BigDecimal assessment, BigDecimal quitRent, BigDecimal legalFee,
			BigDecimal disbursementFee, String propertyAddress,
			String propertyTitleType, Date strataTitleObtainedDate,
			Date keyHandoverDate, Short developmentStage, Set accounts,
			Set progressiveBillings) {
		this.project = project;
		this.unitNo = unitNo;
		this.ptNo = ptNo;
		this.hsdNo = hsdNo;
		this.blockNo = blockNo;
		this.level = level;
		this.layoutType = layoutType;
		this.orientation = orientation;
		this.landArea = landArea;
		this.builtUpArea = builtUpArea;
		this.propertyStatus = propertyStatus;
		this.statusChangeDate = statusChangeDate;
		this.purchasePrice = purchasePrice;
		this.discountAmount = discountAmount;
		this.redemptionAmount = redemptionAmount;
		this.redemptionPaidTodate = redemptionPaidTodate;
		this.assessment = assessment;
		this.quitRent = quitRent;
		this.legalFee = legalFee;
		this.disbursementFee = disbursementFee;
		this.propertyAddress = propertyAddress;
		this.propertyTitleType = propertyTitleType;
		this.strataTitleObtainedDate = strataTitleObtainedDate;
		this.keyHandoverDate = keyHandoverDate;
		this.developmentStage = developmentStage;
		this.accounts = accounts;
		this.progressiveBillings = progressiveBillings;
	}

	public Long getInventoryId() {
		return this.inventoryId;
	}

	public void setInventoryId(Long inventoryId) {
		this.inventoryId = inventoryId;
	}

	public Project getProject() {
		return this.project;
	}

	public void setProject(Project project) {
		this.project = project;
	}

	public String getUnitNo() {
		return this.unitNo;
	}

	public void setUnitNo(String unitNo) {
		this.unitNo = unitNo;
	}

	public String getPtNo() {
		return this.ptNo;
	}

	public void setPtNo(String ptNo) {
		this.ptNo = ptNo;
	}

	public String getHsdNo() {
		return this.hsdNo;
	}

	public void setHsdNo(String hsdNo) {
		this.hsdNo = hsdNo;
	}

	public String getBlockNo() {
		return this.blockNo;
	}

	public void setBlockNo(String blockNo) {
		this.blockNo = blockNo;
	}

	public Short getLevel() {
		return this.level;
	}

	public void setLevel(Short level) {
		this.level = level;
	}

	public String getLayoutType() {
		return this.layoutType;
	}

	public void setLayoutType(String layoutType) {
		this.layoutType = layoutType;
	}

	public String getOrientation() {
		return this.orientation;
	}

	public void setOrientation(String orientation) {
		this.orientation = orientation;
	}

	public Integer getLandArea() {
		return this.landArea;
	}

	public void setLandArea(Integer landArea) {
		this.landArea = landArea;
	}

	public Integer getBuiltUpArea() {
		return this.builtUpArea;
	}

	public void setBuiltUpArea(Integer builtUpArea) {
		this.builtUpArea = builtUpArea;
	}

	public String getPropertyStatus() {
		return this.propertyStatus;
	}

	public void setPropertyStatus(String propertyStatus) {
		this.propertyStatus = propertyStatus;
	}

	public Date getStatusChangeDate() {
		return this.statusChangeDate;
	}

	public void setStatusChangeDate(Date statusChangeDate) {
		this.statusChangeDate = statusChangeDate;
	}

	public BigDecimal getPurchasePrice() {
		return this.purchasePrice;
	}

	public void setPurchasePrice(BigDecimal purchasePrice) {
		this.purchasePrice = purchasePrice;
	}

	public BigDecimal getDiscountAmount() {
		return this.discountAmount;
	}

	public void setDiscountAmount(BigDecimal discountAmount) {
		this.discountAmount = discountAmount;
	}

	public BigDecimal getRedemptionAmount() {
		return this.redemptionAmount;
	}

	public void setRedemptionAmount(BigDecimal redemptionAmount) {
		this.redemptionAmount = redemptionAmount;
	}

	public Date getRedemptionPaidTodate() {
		return this.redemptionPaidTodate;
	}

	public void setRedemptionPaidTodate(Date redemptionPaidTodate) {
		this.redemptionPaidTodate = redemptionPaidTodate;
	}

	public BigDecimal getAssessment() {
		return this.assessment;
	}

	public void setAssessment(BigDecimal assessment) {
		this.assessment = assessment;
	}

	public BigDecimal getQuitRent() {
		return this.quitRent;
	}

	public void setQuitRent(BigDecimal quitRent) {
		this.quitRent = quitRent;
	}

	public BigDecimal getLegalFee() {
		return this.legalFee;
	}

	public void setLegalFee(BigDecimal legalFee) {
		this.legalFee = legalFee;
	}

	public BigDecimal getDisbursementFee() {
		return this.disbursementFee;
	}

	public void setDisbursementFee(BigDecimal disbursementFee) {
		this.disbursementFee = disbursementFee;
	}

	public String getPropertyAddress() {
		return this.propertyAddress;
	}

	public void setPropertyAddress(String propertyAddress) {
		this.propertyAddress = propertyAddress;
	}

	public String getPropertyTitleType() {
		return this.propertyTitleType;
	}

	public void setPropertyTitleType(String propertyTitleType) {
		this.propertyTitleType = propertyTitleType;
	}

	public Date getStrataTitleObtainedDate() {
		return this.strataTitleObtainedDate;
	}

	public void setStrataTitleObtainedDate(Date strataTitleObtainedDate) {
		this.strataTitleObtainedDate = strataTitleObtainedDate;
	}

	public Date getKeyHandoverDate() {
		return this.keyHandoverDate;
	}

	public void setKeyHandoverDate(Date keyHandoverDate) {
		this.keyHandoverDate = keyHandoverDate;
	}

	public Short getDevelopmentStage() {
		return this.developmentStage;
	}

	public void setDevelopmentStage(Short developmentStage) {
		this.developmentStage = developmentStage;
	}

	public Set getAccounts() {
		return this.accounts;
	}

	public void setAccounts(Set accounts) {
		this.accounts = accounts;
	}

	public Set getProgressiveBillings() {
		return this.progressiveBillings;
	}

	public void setProgressiveBillings(Set progressiveBillings) {
		this.progressiveBillings = progressiveBillings;
	}

}
