package com.vipro.data;

// Generated Feb 3, 2013 6:50:08 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * Account generated by hbm2java
 */
public class SalesCommissionHistory implements java.io.Serializable {

	private Long commissionId;
	private Account account;
	private Long projectId;
	private Long batchNo;
	private BigDecimal purchasePrice;
	private BigDecimal claimPercent;
	private BigDecimal claimAmount;
	private String claimStatus;
	private Long submittedBy;
	private Date dateSubmitted;
	private Long verifiedBy;
	private Date dateVerified;
	private Long approvedBy;
	private Date dateApproved;
	private Long changedBy;
	private Date dateChanged;
	
	public SalesCommissionHistory() {
	}

	public SalesCommissionHistory(Account account, Long projectId, BigDecimal purchasePrice, BigDecimal claimPercent, BigDecimal claimAmount, String claimStatus,
			Long submittedBy, Date dateSubmitted, Long verifiedBy, Date dateVerified, Long approvedBy, Date dateApproved, Long changedBy, Date dateChanged) {
		this.account = account;
		this.projectId = projectId;
		this.purchasePrice = purchasePrice;
		this.claimPercent = claimPercent;
		this.claimAmount = claimAmount;
		this.claimStatus = claimStatus;
		this.submittedBy = submittedBy;
		this.dateSubmitted = dateSubmitted;
		this.verifiedBy = verifiedBy;
		this.dateVerified = dateVerified;
		this.approvedBy = approvedBy;
		this.dateApproved = dateApproved;
		this.changedBy = changedBy;
		this.dateChanged = dateChanged;
	}

	public Long getCommissionId() {
		return commissionId;
	}

	public void setCommissionId(Long commissionId) {
		this.commissionId = commissionId;
	}

	public Account getAccount() {
		return this.account;
	}

	public void setAccount(Account account) {
		this.account = account;
	}
	
	public Long getProjectId() {
		return this.projectId;
	}

	public void setProjectId(Long projectId) {
		this.projectId = projectId;
	}
	
	public BigDecimal getPurchasePrice() {
		return purchasePrice;
	}

	public void setPurchasePrice(BigDecimal purchasePrice) {
		this.purchasePrice = purchasePrice;
	}
	
	public BigDecimal getClaimPercent() {
		return claimPercent;
	}

	public void setClaimPercent(BigDecimal claimPercent) {
		this.claimPercent = claimPercent;
	}
	
	public BigDecimal getClaimAmount() {
		return claimAmount;
	}

	public void setClaimAmount(BigDecimal claimAmount) {
		this.claimAmount = claimAmount;
	}
	
	public String getClaimStatus() {
		return claimStatus;
	}

	public void setClaimStatus(String claimStatus) {
		this.claimStatus = claimStatus;
	}
	
	public Date getDateSubmitted() {
		return dateSubmitted;
	}

	public void setDateSubmitted(Date dateSubmitted) {
		this.dateSubmitted = dateSubmitted;
	}

	public Long getApprovedBy() {
		return approvedBy;
	}

	public void setApprovedBy(Long approvedBy) {
		this.approvedBy = approvedBy;
	}

	public Date getDateApproved() {
		return dateApproved;
	}

	public void setDateApproved(Date dateApproved) {
		this.dateApproved = dateApproved;
	}

	public Long getSubmittedBy() {
		return submittedBy;
	}

	public void setSubmittedBy(Long submittedBy) {
		this.submittedBy = submittedBy;
	}

	public Long getBatchNo() {
		return batchNo;
	}

	public void setBatchNo(Long batchNo) {
		this.batchNo = batchNo;
	}
	
	public Long getChangedBy() {
		return changedBy;
	}

	public void setChangedBy(Long changedBy) {
		this.changedBy = changedBy;
	}

	public Date getDateChanged() {
		return dateChanged;
	}

	public void setDateChanged(Date dateChanged) {
		this.dateChanged = dateChanged;
	}

	public Long getVerifiedBy() {
		return verifiedBy;
	}

	public void setVerifiedBy(Long verifiedBy) {
		this.verifiedBy = verifiedBy;
	}

	public Date getDateVerified() {
		return dateVerified;
	}

	public void setDateVerified(Date dateVerified) {
		this.dateVerified = dateVerified;
	}
	
}
