package com.vipro.data;

// Generated Feb 3, 2013 6:50:08 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * ProjectInventory generated by hbm2java
 */
public class SalesCancellationHistory implements java.io.Serializable {

	private Long cancellationId;
	private ProjectInventory projectInventory;
	private BigDecimal registrationFee;
	private String cancelledReason;
	private BigDecimal cancelFee;
	private BigDecimal cancelTax;
	private BigDecimal cancelNetRefundAmt;
	private Long cancelDocId; 
	

	public SalesCancellationHistory() {
	}

	public SalesCancellationHistory(ProjectInventory projectInventory) {
		this.projectInventory = projectInventory;
	}

	public SalesCancellationHistory(Long cancellationId, ProjectInventory projectInventory, BigDecimal registrationFee,
			String cancelledReason, BigDecimal cancelFee, BigDecimal cancelTax, BigDecimal cancelNetRefundAmt, Long cancelDocId) {
		this.cancellationId = cancellationId;
		this.projectInventory = projectInventory;
		this.registrationFee = registrationFee;
		this.cancelledReason = cancelledReason;
		this.cancelFee = cancelFee;
		this.cancelTax = cancelTax;
		this.cancelNetRefundAmt = cancelNetRefundAmt;
		this.cancelDocId = cancelDocId;
	}
	
	public Long getCancellationId() {
		return cancellationId;
	}

	public void setCancellationId(Long cancellationId) {
		this.cancellationId = cancellationId;
	}
	
	public ProjectInventory getProjectInventory() {
		return this.projectInventory;
	}

	public void setProjectInventory(ProjectInventory projectInventory) {
		this.projectInventory = projectInventory;
	}

	public BigDecimal getRegistrationFee() {
		return registrationFee;
	}

	public void setRegistrationFee(BigDecimal registrationFee) {
		this.registrationFee = registrationFee;
	}
	
	public String getCancelledReason() {
		return this.cancelledReason;
	}

	public void setCancelledReason(String cancelledReason) {
		this.cancelledReason = cancelledReason;
	}
	
	public BigDecimal getCancelTax() {
		return cancelTax;
	}

	public void setCancelTax(BigDecimal cancelTax) {
		this.cancelTax = cancelTax;
	}
	
	public BigDecimal getCancelFee() {
		return cancelFee;
	}

	public void setCancelFee(BigDecimal cancelFee) {
		this.cancelFee = cancelFee;
	}
	
	public BigDecimal getCancelNetRefundAmt() {
		return cancelNetRefundAmt;
	}

	public void setCancelNetRefundAmt(BigDecimal cancelNetRefundAmt) {
		this.cancelNetRefundAmt = cancelNetRefundAmt;
	}
	
	public Long getCancelDocId() {
		return cancelDocId;
	}

	public void setCancelDocId(Long cancelDocId) {
		this.cancelDocId = cancelDocId;
	}
		
}
