package com.vipro.data;

// Generated Feb 3, 2013 6:50:08 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * Voucher generated by hbm2java
 */
public class Voucher implements java.io.Serializable {

	private Long voucherId;
	private Customer customer;
	private Date issueDate;
	private String voucherNo;
	private String voucherType;
	private BigDecimal voucherAmount;
	private String status;

	public Voucher() {
	}

	public Voucher(Customer customer) {
		this.customer = customer;
	}

	public Voucher(Customer customer, Date issueDate, String voucherNo,
			String voucherType, BigDecimal voucherAmount, String status) {
		this.customer = customer;
		this.issueDate = issueDate;
		this.voucherNo = voucherNo;
		this.voucherType = voucherType;
		this.voucherAmount = voucherAmount;
		this.status = status;
	}

	public Long getVoucherId() {
		return this.voucherId;
	}

	public void setVoucherId(Long voucherId) {
		this.voucherId = voucherId;
	}

	public Customer getCustomer() {
		return this.customer;
	}

	public void setCustomer(Customer customer) {
		this.customer = customer;
	}

	public Date getIssueDate() {
		return this.issueDate;
	}

	public void setIssueDate(Date issueDate) {
		this.issueDate = issueDate;
	}

	public String getVoucherNo() {
		return this.voucherNo;
	}

	public void setVoucherNo(String voucherNo) {
		this.voucherNo = voucherNo;
	}

	public String getVoucherType() {
		return this.voucherType;
	}

	public void setVoucherType(String voucherType) {
		this.voucherType = voucherType;
	}

	public BigDecimal getVoucherAmount() {
		return this.voucherAmount;
	}

	public void setVoucherAmount(BigDecimal voucherAmount) {
		this.voucherAmount = voucherAmount;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

}
