package com.vipro.data;

// Generated Feb 3, 2013 6:50:08 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * WaterBilling generated by hbm2java
 */
public class WaterBilling implements java.io.Serializable {

	private Long waterId;
	private Account account;
	private Date date;
	private Integer startReading;
	private Integer endReading;
	private BigDecimal rate;
	private BigDecimal amount;
	private String transactionCode;
	private String invoiceNo;

	public WaterBilling() {
	}

	public WaterBilling(Account account) {
		this.account = account;
	}

	public WaterBilling(Account account, Date date, Integer startReading,
			Integer endReading, BigDecimal rate, BigDecimal amount,
			String transactionCode, String invoiceNo) {
		this.account = account;
		this.date = date;
		this.startReading = startReading;
		this.endReading = endReading;
		this.rate = rate;
		this.amount = amount;
		this.transactionCode = transactionCode;
		this.invoiceNo = invoiceNo;
	}

	public Long getWaterId() {
		return this.waterId;
	}

	public void setWaterId(Long waterId) {
		this.waterId = waterId;
	}

	public Account getAccount() {
		return this.account;
	}

	public void setAccount(Account account) {
		this.account = account;
	}

	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	public Integer getStartReading() {
		return this.startReading;
	}

	public void setStartReading(Integer startReading) {
		this.startReading = startReading;
	}

	public Integer getEndReading() {
		return this.endReading;
	}

	public void setEndReading(Integer endReading) {
		this.endReading = endReading;
	}

	public BigDecimal getRate() {
		return this.rate;
	}

	public void setRate(BigDecimal rate) {
		this.rate = rate;
	}

	public BigDecimal getAmount() {
		return this.amount;
	}

	public void setAmount(BigDecimal amount) {
		this.amount = amount;
	}

	public String getTransactionCode() {
		return this.transactionCode;
	}

	public void setTransactionCode(String transactionCode) {
		this.transactionCode = transactionCode;
	}

	public String getInvoiceNo() {
		return this.invoiceNo;
	}

	public void setInvoiceNo(String invoiceNo) {
		this.invoiceNo = invoiceNo;
	}

}
