package com.vipro.data;

// Generated Feb 3, 2013 6:50:08 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * ProjectInventory generated by hbm2java
 */
public class AdjLog implements java.io.Serializable {

	private Long adjLogId;
	private Long adjHeaderId;
	private ProjectInventory projectInventory;
	private BigDecimal purchasePriceBef;
	private BigDecimal discountAmountBef;
	private BigDecimal netAdjBef;
	private BigDecimal discountRateBef;
	private BigDecimal purchasePriceAft;
	private BigDecimal discountAmountAft;
	private BigDecimal netAdjAft;
	private BigDecimal discountRateAft;
    private String status;

	public AdjLog() {
	}
	
	public AdjLog(ProjectInventory projectInventory) {
		this.projectInventory = projectInventory;
	}

	public AdjLog(Long adjLogId, Long adjHeaderId, ProjectInventory projectInventory,BigDecimal purchasePriceBef, BigDecimal discountAmountBef, BigDecimal netAdjBef, 
			BigDecimal discountRateBef, BigDecimal purchasePriceAft, BigDecimal discountAmountAft, BigDecimal netAdjAft, BigDecimal discountRateAft) {
		this.adjLogId = adjLogId;
		this.adjHeaderId = adjHeaderId;
		this.projectInventory = projectInventory;
		this.purchasePriceBef = purchasePriceBef;
		this.discountAmountBef = discountAmountBef;
		this.netAdjBef = netAdjBef;
		this.discountRateBef = discountRateBef;
		this.purchasePriceAft = purchasePriceAft;
		this.discountAmountAft = discountAmountAft;
		this.netAdjAft = netAdjAft;
		this.discountRateAft = discountRateAft;
	}
	
	public Long getAdjLogId() {
		return adjLogId;
	}

	public void setAdjLogId(Long adjLogId) {
		this.adjLogId = adjLogId;
	}
	
	public Long getAdjHeaderId() {
		return adjHeaderId;
	}

	public void setAdjHeaderId(Long adjHeaderId) {
		this.adjHeaderId = adjHeaderId;
	}
	
	public ProjectInventory getProjectInventory() {
		return this.projectInventory;
	}

	public void setProjectInventory(ProjectInventory projectInventory) {
		this.projectInventory = projectInventory;
	}
	
	public BigDecimal getPurchasePriceBef() {
		return purchasePriceBef;
	}

	public void setPurchasePriceBef(BigDecimal purchasePriceBef) {
		this.purchasePriceBef = purchasePriceBef;
	}
	
	public BigDecimal getDiscountAmountBef() {
		return discountAmountBef;
	}

	public void setDiscountAmountBef(BigDecimal discountAmountBef) {
		this.discountAmountBef = discountAmountBef;
	}
	
	public BigDecimal getNetAdjBef() {
		return netAdjBef;
	}

	public void setNetAdjBef(BigDecimal netAdjBef) {
		this.netAdjBef = netAdjBef;
	}
	
	public BigDecimal getDiscountRateBef() {
		return discountRateBef;
	}

	public void setDiscountRateBef(BigDecimal discountRateBef) {
		this.discountRateBef = discountRateBef;
	}
	
	public BigDecimal getPurchasePriceAft() {
		return purchasePriceAft;
	}

	public void setPurchasePriceAft(BigDecimal purchasePriceAft) {
		this.purchasePriceAft = purchasePriceAft;
	}
	
	public BigDecimal getDiscountAmountAft() {
		return discountAmountAft;
	}

	public void setDiscountAmountAft(BigDecimal discountAmountAft) {
		this.discountAmountAft = discountAmountAft;
	}
	
	public BigDecimal getNetAdjAft() {
		return netAdjAft;
	}

	public void setNetAdjAft(BigDecimal netAdjAft) {
		this.netAdjAft = netAdjAft;
	}
	
	public BigDecimal getDiscountRateAft() {
		return discountRateAft;
	}

	public void setDiscountRateAft(BigDecimal discountRateAft) {
		this.discountRateAft = discountRateAft;
	}
	
	public String getStatus() {
		return status;
	}

	public void setStatus(String status) {
		this.status = status;
	}
		
}
