package com.vipro.data;

// Generated Feb 3, 2013 6:50:08 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * AuditLogHeader generated by hbm2java
 */
public class AuditLogHeader implements java.io.Serializable {

	private Long hdrId;
	private Set auditLogDets = new HashSet(0);

	public AuditLogHeader() {
	}

	public AuditLogHeader(Set auditLogDets) {
		this.auditLogDets = auditLogDets;
	}

	public Long getHdrId() {
		return this.hdrId;
	}

	public void setHdrId(Long hdrId) {
		this.hdrId = hdrId;
	}

	public Set getAuditLogDets() {
		return this.auditLogDets;
	}

	public void setAuditLogDets(Set auditLogDets) {
		this.auditLogDets = auditLogDets;
	}

}
