package com.vipro.data;

// Generated Feb 3, 2013 6:50:08 PM by Hibernate Tools 3.4.0.CR1

/**
 * AuditLogDet generated by hbm2java
 */
public class AuditLogDet implements java.io.Serializable {

	private Long detId;
	private AuditLogHeader auditLogHeader;

	public AuditLogDet() {
	}

	public AuditLogDet(AuditLogHeader auditLogHeader) {
		this.auditLogHeader = auditLogHeader;
	}

	public Long getDetId() {
		return this.detId;
	}

	public void setDetId(Long detId) {
		this.detId = detId;
	}

	public AuditLogHeader getAuditLogHeader() {
		return this.auditLogHeader;
	}

	public void setAuditLogHeader(AuditLogHeader auditLogHeader) {
		this.auditLogHeader = auditLogHeader;
	}

}
