package com.vipro.data;

import java.math.BigDecimal;
import java.util.Date;

// Generated Feb 3, 2013 6:50:08 PM by Hibernate Tools 3.4.0.CR1

/**
 * UserProfile generated by hbm2java
 */
public class BillingModel implements java.io.Serializable {

	private Long modelId;
    private Project project;    
	private String billingModelCode;
	private Integer billingSeq;
	private String stage;
	private String description;
	private BigDecimal billingPercentage;
	private Long changedBy;
	private Date dateChanged;
	private String status;

	public BillingModel() {
	}

	public BillingModel(Project project) {
		this.project = project;
	}
	
	public BillingModel(Long modelId, Project project, String billingModelCode,
			Integer billingSeq, String stage, String description, 
			BigDecimal billingPercentage, Long changedBy, Date dateChanged,
			String status) {
		this.setModelId(modelId);
		this.setProject(project);
		this.setBillingModelCode(billingModelCode);
		this.setBillingSeq(billingSeq);
		this.setStage(stage);
		this.setDescription(description);
		this.setBillingPercentage(billingPercentage);
		this.setChangedBy(changedBy);
		this.setDateChanged(dateChanged);
		this.status = status;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public Long getModelId() {
		return modelId;
	}

	public void setModelId(Long modelId) {
		this.modelId = modelId;
	}

	public Date getDateChanged() {
		return dateChanged;
	}

	public void setDateChanged(Date dateChanged) {
		this.dateChanged = dateChanged;
	}

	public Integer getBillingSeq() {
		return billingSeq;
	}

	public void setBillingSeq(Integer billingSeq) {
		this.billingSeq = billingSeq;
	}

	public Project getProject() {
		return project;
	}

	public void setProject(Project project) {
		this.project = project;
	}

	public String getBillingModelCode() {
		return billingModelCode;
	}

	public void setBillingModelCode(String billingModelCode) {
		this.billingModelCode = billingModelCode;
	}

	public String getStage() {
		return stage;
	}

	public void setStage(String stage) {
		this.stage = stage;
	}

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public BigDecimal getBillingPercentage() {
		return billingPercentage;
	}

	public void setBillingPercentage(BigDecimal billingPercentage) {
		this.billingPercentage = billingPercentage;
	}

	public Long getChangedBy() {
		return changedBy;
	}

	public void setChangedBy(Long changedBy) {
		this.changedBy = changedBy;
	}

}
