package com.vipro.data;

// Generated Feb 3, 2013 6:50:08 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * BusinessPartnerId generated by hbm2java
 */
public class BusinessPartnerId implements java.io.Serializable {

	private String partnerId;
	private String partnerType;
	private String businessRegistrationNo;
	private Date registrationDate;
	private String companyName;
	private String address;
	private String contactPersonTitle;
	private String contactPersonName;
	private String officeTel;
	private String faxNo;
	private String mobileNo;
	private String emailAddress;
	private String status;
	private long institutionId;

	public BusinessPartnerId() {
	}

	public BusinessPartnerId(long institutionId) {
		this.institutionId = institutionId;
	}

	public BusinessPartnerId(String partnerId, String partnerType,
			String businessRegistrationNo, Date registrationDate,
			String companyName, String address, String contactPersonTitle,
			String contactPersonName, String officeTel, String faxNo,
			String mobileNo, String emailAddress, String status,
			long institutionId) {
		this.partnerId = partnerId;
		this.partnerType = partnerType;
		this.businessRegistrationNo = businessRegistrationNo;
		this.registrationDate = registrationDate;
		this.companyName = companyName;
		this.address = address;
		this.contactPersonTitle = contactPersonTitle;
		this.contactPersonName = contactPersonName;
		this.officeTel = officeTel;
		this.faxNo = faxNo;
		this.mobileNo = mobileNo;
		this.emailAddress = emailAddress;
		this.status = status;
		this.institutionId = institutionId;
	}

	public String getPartnerId() {
		return this.partnerId;
	}

	public void setPartnerId(String partnerId) {
		this.partnerId = partnerId;
	}

	public String getPartnerType() {
		return this.partnerType;
	}

	public void setPartnerType(String partnerType) {
		this.partnerType = partnerType;
	}

	public String getBusinessRegistrationNo() {
		return this.businessRegistrationNo;
	}

	public void setBusinessRegistrationNo(String businessRegistrationNo) {
		this.businessRegistrationNo = businessRegistrationNo;
	}

	public Date getRegistrationDate() {
		return this.registrationDate;
	}

	public void setRegistrationDate(Date registrationDate) {
		this.registrationDate = registrationDate;
	}

	public String getCompanyName() {
		return this.companyName;
	}

	public void setCompanyName(String companyName) {
		this.companyName = companyName;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getContactPersonTitle() {
		return this.contactPersonTitle;
	}

	public void setContactPersonTitle(String contactPersonTitle) {
		this.contactPersonTitle = contactPersonTitle;
	}

	public String getContactPersonName() {
		return this.contactPersonName;
	}

	public void setContactPersonName(String contactPersonName) {
		this.contactPersonName = contactPersonName;
	}

	public String getOfficeTel() {
		return this.officeTel;
	}

	public void setOfficeTel(String officeTel) {
		this.officeTel = officeTel;
	}

	public String getFaxNo() {
		return this.faxNo;
	}

	public void setFaxNo(String faxNo) {
		this.faxNo = faxNo;
	}

	public String getMobileNo() {
		return this.mobileNo;
	}

	public void setMobileNo(String mobileNo) {
		this.mobileNo = mobileNo;
	}

	public String getEmailAddress() {
		return this.emailAddress;
	}

	public void setEmailAddress(String emailAddress) {
		this.emailAddress = emailAddress;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public long getInstitutionId() {
		return this.institutionId;
	}

	public void setInstitutionId(long institutionId) {
		this.institutionId = institutionId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof BusinessPartnerId))
			return false;
		BusinessPartnerId castOther = (BusinessPartnerId) other;

		return ((this.getPartnerId() == castOther.getPartnerId()) || (this
				.getPartnerId() != null && castOther.getPartnerId() != null && this
				.getPartnerId().equals(castOther.getPartnerId())))
				&& ((this.getPartnerType() == castOther.getPartnerType()) || (this
						.getPartnerType() != null
						&& castOther.getPartnerType() != null && this
						.getPartnerType().equals(castOther.getPartnerType())))
				&& ((this.getBusinessRegistrationNo() == castOther
						.getBusinessRegistrationNo()) || (this
						.getBusinessRegistrationNo() != null
						&& castOther.getBusinessRegistrationNo() != null && this
						.getBusinessRegistrationNo().equals(
								castOther.getBusinessRegistrationNo())))
				&& ((this.getRegistrationDate() == castOther
						.getRegistrationDate()) || (this.getRegistrationDate() != null
						&& castOther.getRegistrationDate() != null && this
						.getRegistrationDate().equals(
								castOther.getRegistrationDate())))
				&& ((this.getCompanyName() == castOther.getCompanyName()) || (this
						.getCompanyName() != null
						&& castOther.getCompanyName() != null && this
						.getCompanyName().equals(castOther.getCompanyName())))
				&& ((this.getAddress() == castOther.getAddress()) || (this
						.getAddress() != null && castOther.getAddress() != null && this
						.getAddress().equals(castOther.getAddress())))
				&& ((this.getContactPersonTitle() == castOther
						.getContactPersonTitle()) || (this
						.getContactPersonTitle() != null
						&& castOther.getContactPersonTitle() != null && this
						.getContactPersonTitle().equals(
								castOther.getContactPersonTitle())))
				&& ((this.getContactPersonName() == castOther
						.getContactPersonName()) || (this
						.getContactPersonName() != null
						&& castOther.getContactPersonName() != null && this
						.getContactPersonName().equals(
								castOther.getContactPersonName())))
				&& ((this.getOfficeTel() == castOther.getOfficeTel()) || (this
						.getOfficeTel() != null
						&& castOther.getOfficeTel() != null && this
						.getOfficeTel().equals(castOther.getOfficeTel())))
				&& ((this.getFaxNo() == castOther.getFaxNo()) || (this
						.getFaxNo() != null && castOther.getFaxNo() != null && this
						.getFaxNo().equals(castOther.getFaxNo())))
				&& ((this.getMobileNo() == castOther.getMobileNo()) || (this
						.getMobileNo() != null
						&& castOther.getMobileNo() != null && this
						.getMobileNo().equals(castOther.getMobileNo())))
				&& ((this.getEmailAddress() == castOther.getEmailAddress()) || (this
						.getEmailAddress() != null
						&& castOther.getEmailAddress() != null && this
						.getEmailAddress().equals(castOther.getEmailAddress())))
				&& ((this.getStatus() == castOther.getStatus()) || (this
						.getStatus() != null && castOther.getStatus() != null && this
						.getStatus().equals(castOther.getStatus())))
				&& (this.getInstitutionId() == castOther.getInstitutionId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getPartnerId() == null ? 0 : this.getPartnerId().hashCode());
		result = 37
				* result
				+ (getPartnerType() == null ? 0 : this.getPartnerType()
						.hashCode());
		result = 37
				* result
				+ (getBusinessRegistrationNo() == null ? 0 : this
						.getBusinessRegistrationNo().hashCode());
		result = 37
				* result
				+ (getRegistrationDate() == null ? 0 : this
						.getRegistrationDate().hashCode());
		result = 37
				* result
				+ (getCompanyName() == null ? 0 : this.getCompanyName()
						.hashCode());
		result = 37 * result
				+ (getAddress() == null ? 0 : this.getAddress().hashCode());
		result = 37
				* result
				+ (getContactPersonTitle() == null ? 0 : this
						.getContactPersonTitle().hashCode());
		result = 37
				* result
				+ (getContactPersonName() == null ? 0 : this
						.getContactPersonName().hashCode());
		result = 37 * result
				+ (getOfficeTel() == null ? 0 : this.getOfficeTel().hashCode());
		result = 37 * result
				+ (getFaxNo() == null ? 0 : this.getFaxNo().hashCode());
		result = 37 * result
				+ (getMobileNo() == null ? 0 : this.getMobileNo().hashCode());
		result = 37
				* result
				+ (getEmailAddress() == null ? 0 : this.getEmailAddress()
						.hashCode());
		result = 37 * result
				+ (getStatus() == null ? 0 : this.getStatus().hashCode());
		result = 37 * result + (int) this.getInstitutionId();
		return result;
	}

}
