package com.vipro.data;

// Generated Feb 7, 2013 12:51:31 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * CaseActivityId generated by hbm2java
 */
public class CaseActivityId implements java.io.Serializable {

	private Long activityId;
	private Long actionBy;
	private String actionCode;
	private Date actionTime;
	private Date oldDueDate;
	private long caseId;

	public CaseActivityId() {
	}

	public CaseActivityId(long caseId) {
		this.caseId = caseId;
	}

	public CaseActivityId(Long activityId, Long actionBy, String actionCode,
			Date actionTime, Date oldDueDate, long caseId) {
		this.activityId = activityId;
		this.actionBy = actionBy;
		this.actionCode = actionCode;
		this.actionTime = actionTime;
		this.oldDueDate = oldDueDate;
		this.caseId = caseId;
	}

	public Long getActivityId() {
		return this.activityId;
	}

	public void setActivityId(Long activityId) {
		this.activityId = activityId;
	}

	public Long getActionBy() {
		return this.actionBy;
	}

	public void setActionBy(Long actionBy) {
		this.actionBy = actionBy;
	}

	public String getActionCode() {
		return this.actionCode;
	}

	public void setActionCode(String actionCode) {
		this.actionCode = actionCode;
	}

	public Date getActionTime() {
		return this.actionTime;
	}

	public void setActionTime(Date actionTime) {
		this.actionTime = actionTime;
	}

	public Date getOldDueDate() {
		return this.oldDueDate;
	}

	public void setOldDueDate(Date oldDueDate) {
		this.oldDueDate = oldDueDate;
	}

	public long getCaseId() {
		return this.caseId;
	}

	public void setCaseId(long caseId) {
		this.caseId = caseId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CaseActivityId))
			return false;
		CaseActivityId castOther = (CaseActivityId) other;

		return ((this.getActivityId() == castOther.getActivityId()) || (this
				.getActivityId() != null && castOther.getActivityId() != null && this
				.getActivityId().equals(castOther.getActivityId())))
				&& ((this.getActionBy() == castOther.getActionBy()) || (this
						.getActionBy() != null
						&& castOther.getActionBy() != null && this
						.getActionBy().equals(castOther.getActionBy())))
				&& ((this.getActionCode() == castOther.getActionCode()) || (this
						.getActionCode() != null
						&& castOther.getActionCode() != null && this
						.getActionCode().equals(castOther.getActionCode())))
				&& ((this.getActionTime() == castOther.getActionTime()) || (this
						.getActionTime() != null
						&& castOther.getActionTime() != null && this
						.getActionTime().equals(castOther.getActionTime())))
				&& ((this.getOldDueDate() == castOther.getOldDueDate()) || (this
						.getOldDueDate() != null
						&& castOther.getOldDueDate() != null && this
						.getOldDueDate().equals(castOther.getOldDueDate())))
				&& (this.getCaseId() == castOther.getCaseId());
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getActivityId() == null ? 0 : this.getActivityId()
						.hashCode());
		result = 37 * result
				+ (getActionBy() == null ? 0 : this.getActionBy().hashCode());
		result = 37
				* result
				+ (getActionCode() == null ? 0 : this.getActionCode()
						.hashCode());
		result = 37
				* result
				+ (getActionTime() == null ? 0 : this.getActionTime()
						.hashCode());
		result = 37
				* result
				+ (getOldDueDate() == null ? 0 : this.getOldDueDate()
						.hashCode());
		result = 37 * result + (int) this.getCaseId();
		return result;
	}

}
