package com.vipro.data;
// Generated Feb 7, 2013 12:56:10 PM by Hibernate Tools 3.4.0.CR1


import java.util.Date;

/**
 * CaseActivity generated by hbm2java
 */
public class CaseActivity  implements java.io.Serializable {


     private Long activityId;
     private Case theCase;
     private Long actionBy;
     private String actionCode;
     private Date actionTime;
     private Date oldDueDate;

    public CaseActivity() {
    }

	
    public CaseActivity(Case theCase) {
        this.theCase = theCase;
    }
    public CaseActivity(Case theCase, Long actionBy, String actionCode, Date actionTime, Date oldDueDate) {
       this.theCase = theCase;
       this.actionBy = actionBy;
       this.actionCode = actionCode;
       this.actionTime = actionTime;
       this.oldDueDate = oldDueDate;
    }
   
    public Long getActivityId() {
        return this.activityId;
    }
    
    public void setActivityId(Long activityId) {
        this.activityId = activityId;
    }
    public Case getCase() {
        return this.theCase;
    }
    
    public void setCase(Case theCase) {
        this.theCase = theCase;
    }
    public Long getActionBy() {
        return this.actionBy;
    }
    
    public void setActionBy(Long actionBy) {
        this.actionBy = actionBy;
    }
    public String getActionCode() {
        return this.actionCode;
    }
    
    public void setActionCode(String actionCode) {
        this.actionCode = actionCode;
    }
    public Date getActionTime() {
        return this.actionTime;
    }
    
    public void setActionTime(Date actionTime) {
        this.actionTime = actionTime;
    }
    public Date getOldDueDate() {
        return this.oldDueDate;
    }
    
    public void setOldDueDate(Date oldDueDate) {
        this.oldDueDate = oldDueDate;
    }




}


