package com.vipro.data;

// Generated Feb 3, 2013 6:50:08 PM by Hibernate Tools 3.4.0.CR1

/**
 * Contact generated by hbm2java
 */
public class Contact implements java.io.Serializable {

	private Long id;
	private ContactList contactList;
	private Customer customer;
	private String contactName;
	private String contactType;
	private String email;
	private String mobileNo;
	private String docTemplateId;

	public Contact() {
	}

	public Contact(ContactList contactList, Customer customer) {
		this.contactList = contactList;
		this.customer = customer;
	}

	public Contact(ContactList contactList, Customer customer,
			String contactName, String contactType, String email,
			String mobileNo, String docTemplateId) {
		this.contactList = contactList;
		this.customer = customer;
		this.contactName = contactName;
		this.contactType = contactType;
		this.email = email;
		this.mobileNo = mobileNo;
		this.docTemplateId = docTemplateId;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public ContactList getContactList() {
		return this.contactList;
	}

	public void setContactList(ContactList contactList) {
		this.contactList = contactList;
	}

	public Customer getCustomer() {
		return this.customer;
	}

	public void setCustomer(Customer customer) {
		this.customer = customer;
	}

	public String getContactName() {
		return this.contactName;
	}

	public void setContactName(String contactName) {
		this.contactName = contactName;
	}

	public String getContactType() {
		return this.contactType;
	}

	public void setContactType(String contactType) {
		this.contactType = contactType;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getMobileNo() {
		return this.mobileNo;
	}

	public void setMobileNo(String mobileNo) {
		this.mobileNo = mobileNo;
	}

	public String getDocTemplateId() {
		return this.docTemplateId;
	}

	public void setDocTemplateId(String docTemplateId) {
		this.docTemplateId = docTemplateId;
	}

}
