package com.vipro.data;

// Generated Feb 3, 2013 6:50:08 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * ContactList generated by hbm2java
 */
public class ContactList implements java.io.Serializable {

	private Long listId;
	private String type;
	private String subject;
	private Set contacts = new HashSet(0);

	public ContactList() {
	}

	public ContactList(String type, String subject, Set contacts) {
		this.type = type;
		this.subject = subject;
		this.contacts = contacts;
	}

	public Long getListId() {
		return this.listId;
	}

	public void setListId(Long listId) {
		this.listId = listId;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getSubject() {
		return this.subject;
	}

	public void setSubject(String subject) {
		this.subject = subject;
	}

	public Set getContacts() {
		return this.contacts;
	}

	public void setContacts(Set contacts) {
		this.contacts = contacts;
	}

}
