package com.vipro.data;

// Generated Feb 3, 2013 6:50:08 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * Discount generated by hbm2java
 */
public class Discount implements java.io.Serializable {

	private long discountId;
	private String description;
	private Date effectiveDate;
	private Date expiryDate;
	private BigDecimal discountRate;
	private Date createdOn;
	private String status;

	public Discount() {
	}

	public Discount(long discountId) {
		this.discountId = discountId;
	}

	public Discount(long discountId, String description, Date effectiveDate,
			Date expiryDate, BigDecimal discountRate, Date createdOn,
			String status) {
		this.discountId = discountId;
		this.description = description;
		this.effectiveDate = effectiveDate;
		this.expiryDate = expiryDate;
		this.discountRate = discountRate;
		this.createdOn = createdOn;
		this.status = status;
	}

	public long getDiscountId() {
		return this.discountId;
	}

	public void setDiscountId(long discountId) {
		this.discountId = discountId;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Date getEffectiveDate() {
		return this.effectiveDate;
	}

	public void setEffectiveDate(Date effectiveDate) {
		this.effectiveDate = effectiveDate;
	}

	public Date getExpiryDate() {
		return this.expiryDate;
	}

	public void setExpiryDate(Date expiryDate) {
		this.expiryDate = expiryDate;
	}

	public BigDecimal getDiscountRate() {
		return this.discountRate;
	}

	public void setDiscountRate(BigDecimal discountRate) {
		this.discountRate = discountRate;
	}

	public Date getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

}
