package com.vipro.data;

// Generated Feb 3, 2013 6:50:08 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * GroupPermission generated by hbm2java
 */
public class GroupPermission implements java.io.Serializable {

	private String permissionId;
	private String name;
	private Set userGroups = new HashSet(0);

	public GroupPermission() {
	}

	public GroupPermission(String permissionId) {
		this.permissionId = permissionId;
	}

	public GroupPermission(String permissionId, String name, Set userGroups) {
		this.permissionId = permissionId;
		this.name = name;
		this.userGroups = userGroups;
	}

	public String getPermissionId() {
		return this.permissionId;
	}

	public void setPermissionId(String permissionId) {
		this.permissionId = permissionId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Set getUserGroups() {
		return this.userGroups;
	}

	public void setUserGroups(Set userGroups) {
		this.userGroups = userGroups;
	}

}
