package com.vipro.data;

// Generated Feb 3, 2013 6:50:08 PM by Hibernate Tools 3.4.0.CR1

/**
 * JoinAccount generated by hbm2java
 */
public class JoinAccount implements java.io.Serializable {

	private JoinAccountId id;
	private Account account;
	private Customer customer;

	public JoinAccount() {
	}

	public JoinAccount(JoinAccountId id, Account account, Customer customer) {
		this.id = id;
		this.account = account;
		this.customer = customer;
	}

	public JoinAccountId getId() {
		return this.id;
	}

	public void setId(JoinAccountId id) {
		this.id = id;
	}

	public Account getAccount() {
		return this.account;
	}

	public void setAccount(Account account) {
		this.account = account;
	}

	public Customer getCustomer() {
		return this.customer;
	}

	public void setCustomer(Customer customer) {
		this.customer = customer;
	}

}
