package com.vipro.data;

// Generated Feb 3, 2013 6:50:08 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * MobilePhone generated by hbm2java
 */
@Deprecated
public class MobilePhone implements java.io.Serializable {

	private Long mobileId;
	private Account account;
	private Customer customer;
	private String mobileNo;
	private Date createdOn;
	private String createdBy;

	public MobilePhone() {
	}

	public MobilePhone(Account account, Customer customer) {
		this.account = account;
		this.customer = customer;
	}

	public MobilePhone(Account account, Customer customer, String mobileNo,
			Date createdOn, String createdBy) {
		this.account = account;
		this.customer = customer;
		this.mobileNo = mobileNo;
		this.createdOn = createdOn;
		this.createdBy = createdBy;
	}

	public Long getMobileId() {
		return this.mobileId;
	}

	public void setMobileId(Long mobileId) {
		this.mobileId = mobileId;
	}

	public Account getAccount() {
		return this.account;
	}

	public void setAccount(Account account) {
		this.account = account;
	}

	public Customer getCustomer() {
		return this.customer;
	}

	public void setCustomer(Customer customer) {
		this.customer = customer;
	}

	public String getMobileNo() {
		return this.mobileNo;
	}

	public void setMobileNo(String mobileNo) {
		this.mobileNo = mobileNo;
	}

	public Date getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

}
