package com.vipro.data;

// Generated Feb 3, 2013 6:50:08 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * Account generated by hbm2java
 */
public class SalesCommissionHistory implements java.io.Serializable {

	private Long commissionId;
	private Account account;
	private Long claimPercent;
	private BigDecimal claimAmount;
	private String claimStatus;
	private Long attendedBy;
	private Date dateSubmitted;
	
	public SalesCommissionHistory() {
	}

	public SalesCommissionHistory(Account account, Long claimPercent, BigDecimal claimAmount, String claimStatus,
			Long attendedBy, Date dateSubmitted) {
		this.account = account;
		this.claimPercent = claimPercent;
		this.claimAmount = claimAmount;
		this.claimStatus = claimStatus;
		this.attendedBy = attendedBy;
		this.dateSubmitted = dateSubmitted;
	}

	public Long getCommissionId() {
		return commissionId;
	}

	public void setCommissionId(Long commissionId) {
		this.commissionId = commissionId;
	}

	public Account getAccount() {
		return this.account;
	}

	public void setAccount(Account account) {
		this.account = account;
	}
	
	public Long getClaimPercent() {
		return claimPercent;
	}

	public void setClaimPercent(Long claimPercent) {
		this.claimPercent = claimPercent;
	}
	
	public BigDecimal getClaimAmount() {
		return claimAmount;
	}

	public void setClaimAmount(BigDecimal claimAmount) {
		this.claimAmount = claimAmount;
	}
	
	public String getClaimStatus() {
		return claimStatus;
	}

	public void setClaimStatus(String claimStatus) {
		this.claimStatus = claimStatus;
	}
	
	public Long getAttendedBy() {
		return attendedBy;
	}

	public void setAttendedBy(Long attendedBy) {
		this.attendedBy = attendedBy;
	}

	public Date getDateSubmitted() {
		return dateSubmitted;
	}

	public void setDateSubmitted(Date dateSubmitted) {
		this.dateSubmitted = dateSubmitted;
	}
	
}
