package com.vipro.data;

// Generated Feb 3, 2013 6:50:08 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * UserGroup generated by hbm2java
 */
public class SeqNo implements java.io.Serializable {

	private String seqType;
	private Long nextSeq;

	public SeqNo() {
	}

	public SeqNo(String seqType) {
		this.setSeqType(seqType);
	}

	public SeqNo(String seqType, Long nextSeq) {
		this.setSeqType(seqType);
		this.setNextSeq(nextSeq);
	}

	public String getSeqType() {
		return seqType;
	}

	public void setSeqType(String seqType) {
		this.seqType = seqType;
	}

	public Long getNextSeq() {
		return nextSeq;
	}

	public void setNextSeq(Long nextSeq) {
		this.nextSeq = nextSeq;
	}

}
