package com.vipro.data;

// Generated Feb 3, 2013 6:50:08 PM by Hibernate Tools 3.4.0.CR1


/**
 * UserGroup generated by hbm2java
 */
public class SeqNo implements java.io.Serializable {

	private Long seqId;
	private String seqType;
	private Long nextSeq;
	private String projectCode;

	public SeqNo() {
	}
	
	public SeqNo(Long seqId) {
		super();
		this.setSeqId(seqId);
	}

	public SeqNo(String seqType) {
		this.setSeqType(seqType);
	}

	public SeqNo(String seqType, Long nextSeq) {
		this.setSeqType(seqType);
		this.setNextSeq(nextSeq);
	}

	public String getSeqType() {
		return seqType;
	}

	public void setSeqType(String seqType) {
		this.seqType = seqType;
	}

	public Long getNextSeq() {
		return nextSeq;
	}

	public void setNextSeq(Long nextSeq) {
		this.nextSeq = nextSeq;
	}

	public String getProjectCode() {
		return projectCode;
	}

	public void setProjectCode(String projectCode) {
		this.projectCode = projectCode;
	}

	public Long getSeqId() {
		return seqId;
	}

	public void setSeqId(Long seqId) {
		this.seqId = seqId;
	}

}
