package com.vipro.data;

// Generated Feb 3, 2013 6:50:08 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * TransactionCode generated by hbm2java
 */
public class TransactionCode implements java.io.Serializable {

	private String transactionCode;
	private String name;
	private String codeType;
	private String accountingGroup;
	private String status;
	private Set transactionHistories = new HashSet(0);
	private Set transactionGroups = new HashSet(0);

	public TransactionCode() {
	}

	public TransactionCode(String transactionCode) {
		this.transactionCode = transactionCode;
	}

	public TransactionCode(String transactionCode, String name,
			String codeType, String accountingGroup, String status,
			Set transactionHistories, Set transactionGroups) {
		this.transactionCode = transactionCode;
		this.name = name;
		this.codeType = codeType;
		this.accountingGroup = accountingGroup;
		this.status = status;
		this.transactionHistories = transactionHistories;
		this.transactionGroups = transactionGroups;
	}

	public String getTransactionCode() {
		return this.transactionCode;
	}

	public void setTransactionCode(String transactionCode) {
		this.transactionCode = transactionCode;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getCodeType() {
		return this.codeType;
	}

	public void setCodeType(String codeType) {
		this.codeType = codeType;
	}

	public String getAccountingGroup() {
		return this.accountingGroup;
	}

	public void setAccountingGroup(String accountingGroup) {
		this.accountingGroup = accountingGroup;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public Set getTransactionHistories() {
		return this.transactionHistories;
	}

	public void setTransactionHistories(Set transactionHistories) {
		this.transactionHistories = transactionHistories;
	}

	public Set getTransactionGroups() {
		return this.transactionGroups;
	}

	public void setTransactionGroups(Set transactionGroups) {
		this.transactionGroups = transactionGroups;
	}

}
