package com.vipro.data;

// Generated Feb 3, 2013 6:50:08 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * TransactionHistory generated by hbm2java
 */
public class TransactionHistory implements java.io.Serializable {

	private Long transactionId;
	private TransactionCode transactionCode;
	private Account account;
	private Date transactionDate;
	private String transactionDescription;
	private String refNo;
	private Date postingDate;
	private Date statementDate;
	private String status;
	private BigDecimal amount;
	
	private String paymentMethod;
	private String bank;
	private String cardChequeNo;

	public TransactionHistory() {
	}

	public TransactionHistory(TransactionCode transactionCode, Account account) {
		this.transactionCode = transactionCode;
		this.account = account;
	}

	public TransactionHistory(TransactionCode transactionCode, Account account,
			Date transactionDate, String transactionDescription, String refNo,
			Date postingDate, Date statementDate, String status) {
		this.transactionCode = transactionCode;
		this.account = account;
		this.transactionDate = transactionDate;
		this.transactionDescription = transactionDescription;
		this.refNo = refNo;
		this.postingDate = postingDate;
		this.statementDate = statementDate;
		this.status = status;
	}

	public String getPaymentMethod() {
		return paymentMethod;
	}

	public void setPaymentMethod(String paymentMethod) {
		this.paymentMethod = paymentMethod;
	}

	public String getBank() {
		return bank;
	}

	public void setBank(String bank) {
		this.bank = bank;
	}

	public String getCardChequeNo() {
		return cardChequeNo;
	}

	public void setCardChequeNo(String cardChequeNo) {
		this.cardChequeNo = cardChequeNo;
	}

	public BigDecimal getAmount() {
		return amount;
	}

	public void setAmount(BigDecimal amount) {
		this.amount = amount;
	}

	public Long getTransactionId() {
		return this.transactionId;
	}

	public void setTransactionId(Long transactionId) {
		this.transactionId = transactionId;
	}

	public TransactionCode getTransactionCode() {
		return this.transactionCode;
	}

	public void setTransactionCode(TransactionCode transactionCode) {
		this.transactionCode = transactionCode;
	}

	public Account getAccount() {
		return this.account;
	}

	public void setAccount(Account account) {
		this.account = account;
	}

	public Date getTransactionDate() {
		return this.transactionDate;
	}

	public void setTransactionDate(Date transactionDate) {
		this.transactionDate = transactionDate;
	}

	public String getTransactionDescription() {
		return this.transactionDescription;
	}

	public void setTransactionDescription(String transactionDescription) {
		this.transactionDescription = transactionDescription;
	}

	public String getRefNo() {
		return this.refNo;
	}

	public void setRefNo(String refNo) {
		this.refNo = refNo;
	}

	public Date getPostingDate() {
		return this.postingDate;
	}

	public void setPostingDate(Date postingDate) {
		this.postingDate = postingDate;
	}

	public Date getStatementDate() {
		return this.statementDate;
	}

	public void setStatementDate(Date statementDate) {
		this.statementDate = statementDate;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

}
