package com.vipro.data;

// Generated Feb 3, 2013 6:50:08 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * UserGroup generated by hbm2java
 */
public class UserGroup implements java.io.Serializable {

	private String groupId;
	private String groupName;
	private String status;
	private Set groupPermissions = new HashSet(0);
	private Set userProfiles = new HashSet(0);

	public UserGroup() {
	}

	public UserGroup(String groupId) {
		this.groupId = groupId;
	}

	public UserGroup(String groupId, String groupName, String status,
			Set groupPermissions, Set userProfiles) {
		this.groupId = groupId;
		this.groupName = groupName;
		this.status = status;
		this.groupPermissions = groupPermissions;
		this.userProfiles = userProfiles;
	}

	public String getGroupId() {
		return this.groupId;
	}

	public void setGroupId(String groupId) {
		this.groupId = groupId;
	}

	public String getGroupName() {
		return this.groupName;
	}

	public void setGroupName(String groupName) {
		this.groupName = groupName;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public Set getGroupPermissions() {
		return this.groupPermissions;
	}

	public void setGroupPermissions(Set groupPermissions) {
		this.groupPermissions = groupPermissions;
	}

	public Set getUserProfiles() {
		return this.userProfiles;
	}

	public void setUserProfiles(Set userProfiles) {
		this.userProfiles = userProfiles;
	}

}
